import './globals.css'
import Nav from './component/nav'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <div className="md:container md:mx-auto px-4">
          {children}
        </div>
      </body>
    </html>
  )
}
